argoproj/pkg

s3/s3.go
Fixes [Argo #1351](https://github.com/argoproj/argo/issues/1351)
minioClient.ListObjectsV2 is not supported by Google Cloud Storage.  s3.IsDirectory and s3.GetDirectory both use ListObjectsV2 to query objects by key prefix.  This gets an error response from GCS.  minioClient.ListObjects is supported by GCS and resolves the above failure in Argo artifact handling for 'directories' of objects.
=> Repalce s3.IsDirectory and GetDirectory use of ListObjectsV2 with ListObjects

Gopkg.lock
The minimum version of aws-sdk-go is documented to be 1.23.13.  This
will be a prerequisite for https://github.com/argoproj/argo/issues/1774
=> Update aws-sdk-go to support IRSA

Gopkg.lock, kubeclientmetrics/metric.go
PR fixes nil pointer dereference error.
<details>
<summary>Sample stack trace:</summary>
```
time="2020-03-18T22:08:22Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 248 [running]:
runtime/debug.Stack(0xc0c8c4f0c0, 0x1b79de0, 0x3252b50)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo-cd/controller.(*ApplicationController).processRequestedAppOperation.func1(0xc0a75c3a40, 0xc0c8c51cc8, 0xc000425400, 0xc0c8c51d68)
/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:664 +0x5a
panic(0x1b79de0, 0x3252b50)
/usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/argoproj/pkg/kubeclientmetrics.(*metricsRoundTripper).RoundTrip(0xc241f79800, 0xc0e2861800, 0x1df2012, 0xd, 0xc1b0eab558) …
```
=> fix: fix nil pointer de-reference in k8s metrics transport wrapper

s3/s3.go
As `filepath.Clean` uses the `os.PathSeparator`, artifact keys like 
`artifact-passing-windows-27z9t/artifact-passing-windows-27z9t-2792197756/foobar` get altered to `artifact-passing-windows-27z9t\artifact-passing-windows-27z9t-2792197756\foobar` when running on Windows (slashes get converted to backslashes). 
Through this, the artifact download of directories within Windows containers fails like here: https://github.com/argoproj/argo/issues/3682#issuecomment-670529620.
Maybe we could also think about if we even need the `filepath.Clean`.
=> fix(s3): Correct key on windows

s3/s3.go
Use `os.PathSeparator` to get cross-plattform compatible filepaths.
After merging, we would also need to create a new git tag to update Argo Workflows to the new version.
=> fix(s3): Use cross-plattform compatible paths

rand/rand.go
This PR adds a lock to the function(s) that use the rand source. I've verified that this code change should not affect the performance of any of the [consumers of these functions in argo-proj/*](https://github.com/search?q=org%3Aargoproj+RandString&type=code).
See parent issue for details: https://github.com/argoproj/argo-cd/issues/4728
=> fix: Data race in RandString()/RandStringCharSet() of argo/pkg, affecting Argo CD unit test (#4728)

grpc/http/forwarders.go
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>
The https://github.com/argoproj/pkg/pull/35 introduced `bufio.Write.Flush` call at the end of steaming call. Unfortunately method crushes if writer is closed. https://github.com/golang/go/issues/9657 We've reproduced it in Argo CD: https://github.com/argoproj/argo-cd/issues/6741
PR ensures uses child context that ends as soon as streaming processing completes which ensure  `bufio.Write.Flush` is not executed on closed context.
=> fix: keepAlive might cause nip pointer dereference panic

grpc/http/forwarders.go, grpc/http/forwarders_test.go
Fix for https://github.com/argoproj/argo-cd/issues/7576
It can happen that during Flush,  w  *bufio.Writer can be nil inside w http.ResponseWriter and it cause panic
As solution I have decided to catch panic and handle it, otherwise I need use reflection for verify nil because it is private field and it may affect performance
Like this 
`v := reflect.ValueOf(w).Elem()
y := v.FieldByName("w")
if !y.IsNil() {
f.Flush()
}`
=> fix: nil pointer during flush

s3/s3.go
Seems like IsDirectory() returns true even when just matching a regular file name - need a slash at the end of the string. Note this is what ListDirectory() does. But I'm curious - did this used to work?
Signed-off-by: Julie Vogelman <julie_vogelman@intuit.com>
=> fix: seems like s3client.IsDirectory() returns true even when just matching a regular file

go.mod, go.sum
v1.7.4 has [this](https://github.com/stretchr/testify/issues/1208) issue
Signed-off-by: Julie Vogelman <julie_vogelman@intuit.com>
=> fix: revert testify module back to one that's working

s3/s3.go
Adds `ServerSideEncryption` in the `GetDirectory` func of the `s3Client`. This fixes access to objects with SSE-C.
Part of https://github.com/argoproj/argo-workflows/issues/9867.
=> fix: add missing ServerSideEncryption param in GetDirectory.

.github/workflows/go.yml, exec/exec_test.go
A recent change in go https://go-review.googlesource.com/c/go/+/403759 changed the behaviour of `os/exec` which the existing test depended on.
In this PR:
* We upgrade the go version used in the `go` workflow
* Improve the test so that it actually tests the error handling of the `exec` module of this package
=> churn: fix exec test under go 1.17+

exec/exec.go, exec/exec_test.go
As seen on https://github.com/argoproj/argo-cd/issues/7898#issuecomment-1353207895, sending `SIGKILL` to `git` processes could leave the local checkout in a locked state.
As also shown in that comment, by passing `SIGTERM` to the `git checkout` process, it is given a chance to gracefully shutdown, leaving the checkout in a state that future operations can succeed.
`SIGKILL` remains as the default signal for timeouts.
--
I'm not too convinced about the `ShouldWait`... it seems reasonable to expect the caller to know if the process should be waited upon or not - in any case, it was a nice way to write the test case for the new functionality.
=> feat: exec - parametrized signal when timeout occurs

s3/s3.go, s3/s3_test.go
Needed for https://github.com/argoproj/argo-workflows/pull/11161
- Allows the caller to set transport in the options.
- Exposes the default transport from minio-go. This is useful since they have some [custom settings](https://github.com/minio/minio-go/blob/68418bf9a5bb03337c8349523a5b188feb5ff2be/transport.go#L41-L43). So the idea is that the caller can reuse as much as possible of the minio-go default transport, only customizing the specific parts they are interested in.
=> feat: expose http transport to callers

expr/function.go, expr/function_test.go, go.mod, go.sum
Recently we noticed that Argo Workflow doesn't support some JSONPath expression to extract some values from inputs. After digging a bit we found that current JSONPath library used by Argo is outdated and it does support only a fraction of the spec. After looking around for better JSONPath libraries I found this one that works for the all expressions I have tried so far: github.com/evilmonkeyinc/jsonpath
If you're also curious about other libraries you can see a comparison here but keep in mind that it's either outdated or incorrect: https://asaiyusuke.github.io/jsonpath/cburgmer-json-path-comparison/docs/index.html
Because I tried some of the JSONPath libraries listed there, including the one written by the author of the post above and most of the expressions in the comparison table …
=> Use more up-to-date and comprehensive JSONPath library

s3/s3.go, s3/s3_test.go
This PR adds support for the S3 client to use ephemeral IAM credentials (e.g. an access/secret key pair + session token obtain through an assume role operation) or to use the new [S3 access grants](https://aws.amazon.com/blogs/storage/scaling-data-access-with-amazon-s3-access-grants/) feature.
This is a pre-requisite to https://github.com/argoproj/argo-workflows/issues/5446
The relevant PR in Argo Workflows is here: https://github.com/argoproj/argo-workflows/pull/12467
I found the contributing guidelines for Argo Workflows, but couldn't find anything for this specific repo, so please let me know if anything is missing. Thank you!
=> feat: Add support for session tokens to S3 client

s3/s3.go
Attempt to fix https://github.com/argoproj/argo-workflows/issues/13248
`fi` is null in the stack trace, and `err` isn't being checked here. So check `err` and don't attempt to continue.
=> fix(s3): check for errors when finding artifacts

cli/cli.go, exec/exec.go, file/file.go, go.mod, go.sum, kube/errors/errors.go, s3/s3.go, time/time.go
addresses https://github.com/argoproj/argo-workflows/pull/13673#discussion_r1779818942
=> refactor(deps): replace unmaintained `pkg/errors` with `fmt.Errorf`

s3/s3.go
This checksum is required if a bucket has Object Lock enabled by default.
addresses https://github.com/argoproj/argo-workflows/issues/11182
=> add flag to enable MD5 checksum for S3 upload

env/env.go, expr/function.go, jwt/zjwt/zjwt.go
These functions aren't used in any Argo project. We should deprecate and remove them.
https://github.com/argoproj/argo-cd/issues/22175
=> chore: deprecate unused functions
